name: warenb
description: this is a fashion app

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  provider: ^6.0.3
  intl: ^0.17.0
  uuid: ^3.0.6
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/